### PR TITLE
Make sure to specify user_data size when calling pw_core_get_registry().

### PR DESCRIPTION
**Pull request by sonata-chen**

### CODE REVIEW

**Comment by xunil-cloud** [comment]
I don't think we need to do this. I have read the code from `src/tools/pw-dot.c` and `/doc/tutorial6.md` , `user_data_size` is set  to zero. It seems that `user_data_size` is not related with `data data` we passed into the event handler.

**Comment by sonata-chen** [comment]
Yep, but i do see `user_data_size` is used on `pw_proxy`,

https://github.com/xunil-cloud/pw-catia/blob/d0b1ab5e0d3b29f9d95f249ed294efd7ff2bcf06/src/main.c#L43-L44
https://github.com/xunil-cloud/pw-catia/blob/d0b1ab5e0d3b29f9d95f249ed294efd7ff2bcf06/src/main.c#L74-L81

why?

**Comment by sonata-chen** [comment]
I try to do some crazy thing, and it will crash!

``` diff
diff --git a/src/main.c b/src/main.c
index f218389..8b3beea 100644
--- a/src/main.c
+++ b/src/main.c
@@ -12,6 +12,7 @@ struct data {
     struct spa_hook registry_listener;

     struct spa_list globals;
+    double test[1000000];
 };

 struct global {
@@ -41,6 +42,7 @@ static void handle_registry_event_global(void *data,
                                          uint32_t version,
                                          const struct spa_dict *props) {
     struct data *d = data;
+    printf("%f", d->test[999999]);
     struct global *g;
     uint32_t client_version;
     struct pw_proxy *proxy;

```

**Comment by sonata-chen** [comment]
> I don't think we need to do this.

Yep, i agree with you. 

We need to specify `user_data_size` when creating `pw_proxy` because pipewire will allocate memories for us, which is not the case for `pw_registry`. 

https://github.com/xunil-cloud/pw-catia/blob/d0b1ab5e0d3b29f9d95f249ed294efd7ff2bcf06/src/main.c#L37-L44

The `data` object we recieved here is simply the object we create in main function which is allocated on the stack.

**Comment by xunil-cloud** [comment]
Ah, didn't realize `pw_registry_bind()` would allocate memory on heap. Thanks for pointing out differences. Closing this PR now.

**Pull request closed without merging**
